# intersection, roads, road2, protected_turn, lanes_total, median,  

# roads,road2: road segment ID where count is taken.  Used to link to table for traffic count
# protected_turn: 0:none, 2: in one direction, 4: in both directions
# lanes_total: sum of both roads.  If I have a 4 lanes in each direction, I will call it 8.  Expect 4, 6, 8 primarily, but might have some one ways as well.
# median: 0:none, 2: in one direction, 4: in both directions 
# exit:  is it an exit for the highway (I55, I94, LSD, etc.)

# GET POSTED SPEED LIMIT FROM CRASH DATA

int_chars = {
'111TH AND HALSTED': {'roads':['28 West', '11600 South'], 
                    'protected_turn': 2, 
                    'total_lanes': 6, 
                    'medians': 2, 
                    'exit': 0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                     'angled':1,
                     },

'115TH AND HALSTED': {'roads':['714 West','11600 South'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians': 2, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                     },
                    
'119TH AND HALSTED': {'roads':['446 West','11600 South'], 
                    'protected_turn': 4, 
                    'total_lanes':6, 
                    'medians': 2, 
                    'exit':0, 
                    'split':0,
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     },
                    
'31ST AND CALIFORNIA':{'roads':['2825 West','3026 South'], 
                    'protected_turn':3, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0,
                    'no_left':0,
                    'angled':0,
                    'triangle':0,

                      }, 
                      
                    
'31ST ST AND MARTIN LUTHER KING DRIVE':{'roads':['440 East','3030 South'], 
                    'protected_turn':4,
                    'total_lanes':10,
                    'medians':2,
                    'exit':0,
                    'split':1, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':2,
                    'angled':0,
                    'triangle':0,
                    },  

                      
'35TH AND WESTERN': {'roads':['2307 West','3636 South'], 
                    'protected_turn': 2, 
                    'total_lanes': 10, 
                    'medians': 1, 
                    'exit': 0, 
                    'split':1, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                    },  
    
'4700 WESTERN': {'roads':['2738 West','4855 South'], 
                    'protected_turn':3, 
                    'total_lanes':12,
                    'medians':1, 
                    'exit':0, 
                    'split':1, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,},            

'55TH AND KEDZIE':{'roads':[ '3105 West','5413 South'], 
                    'protected_turn': 4, 
                    'total_lanes': 8, 
                    'medians': 0, 
                    'exit': 0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                  },   
    
'55TH AND WESTERN':{'roads':['2230 West','5420 South'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':5, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                   },    
    
'55TH and PULASKI':{'roads':['4630 West','5231 South'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                   },  

'63RD AND STATE':{'roads':['120 East','6416 South'],
                    'protected_turn':2, 
                    'total_lanes':6, 
                    'medians':2, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':2, 
                    'no_left':2,
                    'angled':0,
                    'triangle':0,},  
    
'71ST AND ASHLAND':{'roads':['1708 West','7132 South'], 
                    'protected_turn':2, 
                    'total_lanes':6, 
                    'medians':2, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,}, 
    
'75TH AND STATE':{'roads':['46 East','7539 South'], 
                    'protected_turn': 0,
                    'total_lanes': 4,
                    'medians': 1, 
                    'exit': 1, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                 },  
    
'79TH AND HALSTED':{'roads':['540 West','8357 South'], 
                    'protected_turn': 2, 
                    'total_lanes': 6, 
                    'medians': 1, 
                    'exit': 0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                   },        
    
'79TH AND KEDZIE':{'roads':['2830 West','8220 South'], 
                    'protected_turn': 2, 
                    'total_lanes':8, 
                    'medians': 2, 
                    'exit': 0, 
                    'split':0, 
                    'way':4, 
                    'underpass':2, 
                    'no_left':2,
                    'angled':0,
                    'triangle':1,
                  },  
    
'83RD AND STONY ISLAND':{'roads':['1240 East','8216 South'], 
                    'protected_turn':2, 
                    'total_lanes': 8, 
                    'medians': 2, 
                    'exit': 0, 
                    'split':1, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':2,
                    'angled':0,
                    'triangle':0,},  

    
'87TH AND VINCENNES':{'roads':['710 West','8940 South'], 
                    'protected_turn':2, 
                    'total_lanes': 8, 
                    'medians': 1, 
                    'exit': 0, 
                    'split':0, 
                    'way':4, 
                    'underpass':1, 
                    'no_left':0,
                    'angled':1,
                    'triangle':0,
                     },  
  
    
'95TH AND STONEY ISLAND':{'roads':['1916 East','9348 South'], 
                    'protected_turn':4, 
                    'total_lanes': 12, 
                    'medians': 0, 
                    'exit': 0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                    }, 

    
'99TH AND HALSTED':{'roads':['1916 East'], # only had one road with traffic data, other was lesser used side street.
                    'protected_turn':0, 
                    'total_lanes': 6, 
                    'medians': 1, 
                    'exit': 1, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                   }, 
    
  
'ADDISON AND HARLEM':{'roads':['7121 West','3250 North'],  
                    'protected_turn':4, 
                    'total_lanes': 8, 
                    'medians': 0, 
                    'exit': 0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     }, 
    
    
'ARCHER AND CICERO':{'roads':['5410 South','5858 South'],
                    'protected_turn':4, 
                    'total_lanes': 12, 
                    'medians': 0, 
                    'exit': 0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':1,
                    'triangle':0,
                    }, 
   
    
'ARCHER/NARRAGANSETT AND 55TH':{'roads':['6607 West', '6247 South', '6231 South'],
                    'protected_turn':2, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':5, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':1,
                    'triangle':1,
                    }, 
    
'ASHLAND AND 47TH':{'roads':['1439 West', '4432 South'], 
                    'protected_turn':2, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':5, # weird side street
                    'underpass':0, 
                    'no_left':0,
                    'angled':1,
                    'triangle':1,
                    }, 
    
'ASHLAND AND 63RD':{'roads':['1445 West', '6217 South'], 
                    'protected_turn':2, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                    }, 

'ASHLAND AND 87TH':{'roads':['1428 West', '8212 South'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                    },    
    
'ASHLAND AND 95TH':{'roads':['1500 West', '8822 South'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                    },    

    
'ASHLAND AND ARCHER':{'roads':['3229 South', '3247 South'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':1,
                    'triangle':1,
                    }, 
    
    
'ASHLAND AND DIVERSEY':{'roads':['1614 West', '2855 North'], 
                    'protected_turn':2, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':1, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                    }, 
    
'ASHLAND AND DIVISION':{'roads':['1925 West', '1345 North'], 
                    'protected_turn':2, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':1,
                    'angled':0,
                    'triangle':1,
                    }, 
    
    
'ASHLAND AND FULLERTON':{'roads':['1434 West', '2435 North'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':1,
                    },
    
'ASHLAND AND IRVING PARK':{'roads':['1625 West', '4034 North'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                    }, 
    
'ASHLAND AND LAWRENCE':{'roads':['1350 West', '5116 North'], 
                    'protected_turn':4, 
                    'total_lanes':7, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,   
                          }, 
    
'ASHLAND AND MADISON':{'roads':['1650 West', '133 South'], 
                    'protected_turn':0, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':1,
                          }, 
    
'AUSTIN AND ADDISON':{'roads':['6050 West', '3521 North'], 
                    'protected_turn':0, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          },  


'AUSTIN AND IRVING PARK' :{'roads':['5842 West', '4308 North'], 
                    'protected_turn':0, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          },  
 

    
    
'BELMONT AND KEDZIE' :{'roads':['3317 West', '3235 North'], 
                    'protected_turn':2, 
                    'total_lanes':6, 
                    'medians':1, 
                    'exit':1, 
                    'split':0, 
                    'way':5, 
                    'underpass':2, 
                    'no_left':0,
                    'angled':1,
                    'triangle':1,
                          },  

'BLUE ISLAND AND DAMEN' :{'roads':['3317 West', '2358 South'], 
                    'protected_turn':2, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':1,
                    'triangle':0,
                          },  


'BROADWAY/SHERIDAN AND DEVON' :{'roads':['2307 West', '6629 North'], 
                    'protected_turn':2, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':2,
                    'angled':0,
                    'triangle':1,
                          },  

'CALIFORNIA AND DEVON' :{'roads':['2307 West', '6526 North'], 
                    'protected_turn':0, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          },  

    
'CALIFORNIA AND DEVON' :{'roads':['2307 West', '6526 North'], 
                    'protected_turn':0, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          },  

 
    
'CALIFORNIA AND DIVERSEY' :{'roads':['3120 West', '3242 North'], 
                    'protected_turn':2, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':1, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          }, 
    
    
    
'CALIFORNIA AND PETERSON' :{'roads':['2314 West', '5831 North'], 
                    'protected_turn':4, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          }, 
    
    
    
'CANAL AND ROOSEVELT':{'roads':['412 West', '460 South'], 
                    'protected_turn':4, 
                    'total_lanes':10, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          }, 
    
    
    
'CENTRAL AND ADDISON':{'roads':['5434 West', '3501 North'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          }, 
    
    
'CENTRAL AND BELMONT':{'roads':['5532 West', '3501 North'], 
                    'protected_turn':4, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          },
    
'CENTRAL AND CHICAGO':{'roads':['4444 West', '643 North'], 
                    'protected_turn':0, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          }, 
    
    
    
'CENTRAL AND DIVERSEY':{'roads':['5900 West', '2459 North'], 
                    'protected_turn':4, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          }, 
    
    
'CENTRAL AND FULLERTON':{'roads':['5400 West', '2366 North'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          }, 
    
    
'CENTRAL AND IRVING PARK':{'roads':['5301 West', '3658 North'], 
                    'protected_turn':4, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          }, 

'CENTRAL AND LAKE':{'roads':['5838 West', '643 North'], 
                    'protected_turn':1, 
                    'total_lanes':6, 
                    'medians':1, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':1, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          },    

'CENTRAL AND MILWAUKEE':{'roads':['5601 West', '5601 North'], 
                    'protected_turn':1, 
                    'total_lanes':10, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':5, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':1,
                    'triangle':1,
                          },  
 
    
    
'CERMAK AND PULASKI':{'roads':['4042 West', '2119 South'], 
                    'protected_turn':1, 
                    'total_lanes':8, 
                    'medians':2, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':1,
                          },  
    

'CHICAGO AND CLARK':{'roads':['54 West', '835 North'], 
                    'protected_turn':1, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':1,
                          },  

    
'CICERO AND 47TH':{'roads':['4706 West', '4310 South'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':0,
                          },  
    
    
    
'CICERO AND ADDISON':{'roads':['4550 West', '3647 North'], 
                    'protected_turn':4, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':0,
                          },  
    
    
'CICERO AND ARMITAGE':{'roads':['4459 West', '2125 North'], 
                    'protected_turn':2, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':0,
                          },  
    
'CICERO AND ARMITAGE':{'roads':['4459 West', '2125 North'], 
                'protected_turn':2, 
                'total_lanes':6, 
                'medians':0, 
                'exit':0, 
                'split':0, 
                'way':4, 
                'underpass':0, 
                'no_left':0,
                'angled':0,
                'triangle':0,
                 'one_way':0,
                      },  
}




'''


,
, 
'CICERO AND CHICAGO', 
'CICERO AND DIVERSEY',
'CICERO AND FULLERTON', 
'CICERO AND HARRISON', 
'CICERO AND I55',
'CICERO AND NORTH', 
'CICERO AND PETERSON', 
'CICERO AND WASHINGTON',
'CLARK AND FULLERTON', 
'CLARK AND IRVING PARK',
'COLUMBUS AND ILLINOIS', 
'CORNELL DRIVE AND 57TH',
'CORTLAND AND ASHLAND', 
'COTTAGE GROVE AND 71ST',
'COTTAGE GROVE AND 95TH', 
'DAMEN AND 63RD', 
'DAMEN AND DIVERSEY',
'DAMEN AND ELSTON', 
'DAMEN AND FULLERTON',
'DIVERSEY AND AUSTIN',
'DIVERSEY AND WESTERN',
'DIVISION AND DAMEN',
'ELSTON AND ADDISON',
'ELSTON AND FOSTER', 
'ELSTON AND IRVING PARK',
'ELSTON AND LAWRENCE', 
'FOSTER AND BROADWAY',
'FOSTER AND NAGLE',
'FOSTER AND NORTHWEST HIGHWAY',
'FULLERTON AND NARRAGANSETT',
'GARFIELD AND ASHLAND',
'GRAND AND OAK PARK', 
'HALSTED AND 103RD',
'HALSTED AND 63RD',
'HALSTED AND 83RD', 
'HALSTED AND 95TH',
'HALSTED AND DIVISION',
'HALSTED AND FULLERTON',
'HALSTED AND MADISON', 
'HALSTED AND NORTH', 
'HAMLIN AND LAKE',
'HAMLIN AND MADISON', 
'HARLEM AND BELMONT',
'HARLEM AND NORTHWEST HWY',
'HOLLYWOOD AND SHERIDAN',
'HOMAN/KIMBALL AND NORTH', 
'IRVING PARK AND CALIFORNIA',
'IRVING PARK AND KEDZIE', 
'IRVING PARK AND KILPATRICK',
'IRVING PARK AND LARAMIE', 
'IRVING PARK AND NARRAGANSETT',
'JEFFERY AND 79TH', 
'JEFFERY AND 95TH', 
'KEDZIE AND 26TH',
'KEDZIE AND 31ST', 
'KEDZIE AND 47TH', 
'KEDZIE AND 63RD',
'KEDZIE AND 71ST', 
'KEDZIE AND ARMITAGE', 
'KIMBALL AND DIVERSEY',
'KIMBALL AND LINCOLN', 
'KOSTNER AND NORTH', 
'LAFAYETTE AND 87TH',
'LAKE AND UPPER WACKER',
'LAKE SHORE DR AND BELMONT',
'LARAMIE AND FULLERTON',
'LARAMIE AND MADISON',
'LASALLE AND KINZIE',
'LAWRENCE AND CICERO',
'LAWRENCE AND WESTERN', 
'LINCOLN AND MCCORMICK',
'MADISON AND CENTRAL', 
'MADISON AND WESTERN',
'MICHIGAN AND JACKSON', 
'MICHIGAN AND ONTARIO',
'MILWAUKEE AND CENTRAL', 
'MILWAUKEE AND DEVON',
'MILWAUKEE AND MONTROSE', 
'MONTROSE AND WESTERN',
'NORTHWEST HIGHWAY AND FOSTER', 
'OGDEN AND KOSTNER',
'PERSHING AND WESTERN', 
'PETERSON AND WESTERN',
'PULASKI AND 63RD',
'PULASKI AND 79TH', 
'PULASKI AND ARCHER', 
'PULASKI AND ARMITAGE',
'PULASKI AND BELMONT', 
'PULASKI AND CHICAGO',
'PULASKI AND DIVERSEY', 
'PULASKI AND DIVISION',
'PULASKI AND FOSTER', 
'PULASKI AND FULLERTON',
'PULASKI AND IRVING PARK',
'PULASKI AND LAWRENCE',
'PULASKI AND MONTROSE', 
'PULASKI AND NORTH',
'PULASKI AND PETERSON',
'RIDGE AND CLARK', 
'ROOSEVELT AND HALSTED',
'ROOSEVELT AND KOSTNER', 
'ROOSEVELT AND PULASKI',
'SACRAMENTO AND CHICAGO', 
'SACRAMENTO AND LAKE',
'SHERIDAN AND FOSTER', 
'STATE AND 79TH', 
'STONEY ISLAND AND 76TH',
'STONEY ISLAND AND 79TH',
'STONY ISLAND/CORNELL AND 67TH',
'TOUHY AND OSCEOLA', 
'VAN BUREN AND WESTERN',
'VINCENNES AND 111TH', 
'WENTWORTH AND GARFIELD',
'WESTERN AND 51ST', 
'WESTERN AND 63RD', 
'WESTERN AND 71ST',
'WESTERN AND 79TH', 
'WESTERN AND ADDISON',
'WESTERN AND ARMITAGE',
'WESTERN AND CERMAK',
'WESTERN AND CHICAGO',
'WESTERN AND DEVON',
'WESTERN AND FOSTER', 
'WESTERN AND FULLERTON',
'WESTERN AND MARQUETTE', 
'WESTERN AND NORTH',
'WESTERN AND PRATT',
'WESTERN AND TOUHY'

'''