# intersection, roads, road2, protected_turn, lanes_total, median,  

# roads: road segment ID where count is taken.  Used to link to table for traffic count
# protected_turn: 0:none, 2:in one direction, 4:in all directions etc.
# total_lanes: sum of all roads.  If I have a 4 lanes in each direction, I will call it 8.  Turn lanes not counted.  Bus lanes not counted.
# median: 0:none, How many physical medians are there.  Splits and underpasses were also counted as medians.
# exit:  is it an exit for the highway (I55, I94, LSD, etc.).  If it has a ramp within 100 m, I counted it.
# split: Is the N/S or E/W sides divided with an extra set of lights between intersection.  Will include example in presentation.
# way:  How many roads intersect.  Typical is 4.  We also have a lot of 6 way in chicago
# underpass: Chicago has a lot of narrow lane underpasses that feed directly to int. Hard to see, and very narrow.
# no_left:  How many directions have a no left turn sign.  Sometimes seen in congested areas.  
# angled: 0 if right angled.  1 if angled >=30 deg
# triangle: part of larger triangle intersection of 3 or more roads.  Within 100m in each direction.
# oneway: how many LANES are 1 way in my intersection?

# would also like to add turnlanes and lat/long

# GET POSTED SPEED LIMIT FROM CRASH DATA

int_chars = {
'111TH AND HALSTED': {'roads':['28 West', '11600 South'], 
                    'protected_turn': 2, 
                    'total_lanes': 6, 
                    'medians': 2, 
                    'exit': 0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':1,
                    'triangle':0,
                     },

'115TH AND HALSTED': {'roads':['714 West','11600 South'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians': 2, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                     },
                    
'119TH AND HALSTED': {'roads':['446 West','11600 South'], 
                    'protected_turn': 4, 
                    'total_lanes':6, 
                    'medians': 2, 
                    'exit':0, 
                    'split':0,
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     },
                    
'31ST AND CALIFORNIA':{'roads':['2825 West','3026 South'], 
                    'protected_turn':3, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0,
                    'no_left':0,
                    'angled':0,
                    'triangle':0,

                      }, 
                      
                    
'31ST ST AND MARTIN LUTHER KING DRIVE':{'roads':['440 East','3030 South'], 
                    'protected_turn':4,
                    'total_lanes':10,
                    'medians':2,
                    'exit':0,
                    'split':1, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':2,
                    'angled':0,
                    'triangle':0,
                    },  

                      
'35TH AND WESTERN': {'roads':['2307 West','3636 South'], 
                    'protected_turn': 2, 
                    'total_lanes': 10, 
                    'medians': 1, 
                    'exit': 0, 
                    'split':1, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                    },  
    
'4700 WESTERN': {'roads':['2738 West','4855 South'], 
                    'protected_turn':3, 
                    'total_lanes':12,
                    'medians':1, 
                    'exit':0, 
                    'split':1, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,},            

'55TH AND KEDZIE':{'roads':[ '3105 West','5413 South'], 
                    'protected_turn': 4, 
                    'total_lanes': 8, 
                    'medians': 0, 
                    'exit': 0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                  },   
    
'55TH AND WESTERN':{'roads':['2230 West','5420 South'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':5, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                   },    
    
'55TH and PULASKI':{'roads':['4630 West','5231 South'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                   },  

'63RD AND STATE':{'roads':['120 East','6416 South'],
                    'protected_turn':2, 
                    'total_lanes':6, 
                    'medians':2, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':2, 
                    'no_left':2,
                    'angled':0,
                    'triangle':0,},  
    
'71ST AND ASHLAND':{'roads':['1708 West','7132 South'], 
                    'protected_turn':2, 
                    'total_lanes':6, 
                    'medians':2, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,}, 
    
'75TH AND STATE':{'roads':['46 East','7539 South'], 
                    'protected_turn': 0,
                    'total_lanes': 4,
                    'medians': 1, 
                    'exit': 1, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                 },  
    
'79TH AND HALSTED':{'roads':['540 West','8357 South'], 
                    'protected_turn': 2, 
                    'total_lanes': 6, 
                    'medians': 1, 
                    'exit': 0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                   },        
    
'79TH AND KEDZIE':{'roads':['2830 West','8220 South'], 
                    'protected_turn': 2, 
                    'total_lanes':8, 
                    'medians': 2, 
                    'exit': 0, 
                    'split':0, 
                    'way':4, 
                    'underpass':2, 
                    'no_left':2,
                    'angled':0,
                    'triangle':1,
                  },  
    
'83RD AND STONY ISLAND':{'roads':['1240 East','8216 South'], 
                    'protected_turn':2, 
                    'total_lanes': 8, 
                    'medians': 2, 
                    'exit': 0, 
                    'split':1, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':2,
                    'angled':0,
                    'triangle':0,},  

    
'87TH AND VINCENNES':{'roads':['710 West','8940 South'], 
                    'protected_turn':2, 
                    'total_lanes': 8, 
                    'medians': 1, 
                    'exit': 0, 
                    'split':0, 
                    'way':4, 
                    'underpass':1, 
                    'no_left':0,
                    'angled':1,
                    'triangle':0,
                     },  
  
    
'95TH AND STONEY ISLAND':{'roads':['1916 East','9348 South'], 
                    'protected_turn':4, 
                    'total_lanes': 12, 
                    'medians': 0, 
                    'exit': 0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                    }, 

    
'99TH AND HALSTED':{'roads':['1916 East'], # only had one road with traffic data, other was lesser used side street.
                    'protected_turn':0, 
                    'total_lanes': 6, 
                    'medians': 1, 
                    'exit': 1, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                   }, 
    
  
'ADDISON AND HARLEM':{'roads':['7121 West','3250 North'],  
                    'protected_turn':4, 
                    'total_lanes': 8, 
                    'medians': 0, 
                    'exit': 0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     }, 
    
    
'ARCHER AND CICERO':{'roads':['5410 South','5858 South'],
                    'protected_turn':4, 
                    'total_lanes': 12, 
                    'medians': 0, 
                    'exit': 0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':1,
                    'triangle':0,
                    }, 
   
    
'ARCHER/NARRAGANSETT AND 55TH':{'roads':['6607 West', '6247 South', '6231 South'],
                    'protected_turn':2, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':5, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':1,
                    'triangle':1,
                    }, 
    
'ASHLAND AND 47TH':{'roads':['1439 West', '4432 South'], 
                    'protected_turn':2, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':5, # weird side street
                    'underpass':0, 
                    'no_left':0,
                    'angled':1,
                    'triangle':1,
                    }, 
    
'ASHLAND AND 63RD':{'roads':['1445 West', '6217 South'], 
                    'protected_turn':2, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                    }, 

'ASHLAND AND 87TH':{'roads':['1428 West', '8212 South'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                    },    
    
'ASHLAND AND 95TH':{'roads':['1500 West', '8822 South'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                    },    

    
'ASHLAND AND ARCHER':{'roads':['3229 South', '3247 South'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':1,
                    'triangle':1,
                    }, 
    
    
'ASHLAND AND DIVERSEY':{'roads':['1614 West', '2855 North'], 
                    'protected_turn':2, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':1, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                    }, 
    
'ASHLAND AND DIVISION':{'roads':['1925 West', '1345 North'], 
                    'protected_turn':2, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':1,
                    'angled':0,
                    'triangle':1,
                    }, 
    
    
'ASHLAND AND FULLERTON':{'roads':['1434 West', '2435 North'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':1,
                    },
    
'ASHLAND AND IRVING PARK':{'roads':['1625 West', '4034 North'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                    }, 
    
'ASHLAND AND LAWRENCE':{'roads':['1350 West', '5116 North'], 
                    'protected_turn':4, 
                    'total_lanes':7, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,   
                          }, 
    
'ASHLAND AND MADISON':{'roads':['1650 West', '133 South'], 
                    'protected_turn':0, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':1,
                          }, 
    
'AUSTIN AND ADDISON':{'roads':['6050 West', '3521 North'], 
                    'protected_turn':0, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          },  


'AUSTIN AND IRVING PARK' :{'roads':['5842 West', '4308 North'], 
                    'protected_turn':0, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          },  
 

    
    
'BELMONT AND KEDZIE' :{'roads':['3317 West', '3235 North'], 
                    'protected_turn':2, 
                    'total_lanes':6, 
                    'medians':1, 
                    'exit':1, 
                    'split':0, 
                    'way':5, 
                    'underpass':2, 
                    'no_left':0,
                    'angled':1,
                    'triangle':1,
                          },  

'BLUE ISLAND AND DAMEN' :{'roads':['3317 West', '2358 South'], 
                    'protected_turn':2, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':1,
                    'triangle':0,
                          },  


'BROADWAY/SHERIDAN AND DEVON' :{'roads':['2307 West', '6629 North'], 
                    'protected_turn':2, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':2,
                    'angled':0,
                    'triangle':1,
                          },  

'CALIFORNIA AND DEVON' :{'roads':['2307 West', '6526 North'], 
                    'protected_turn':0, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          },  

    
'CALIFORNIA AND DEVON' :{'roads':['2307 West', '6526 North'], 
                    'protected_turn':0, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          },  

 
    
'CALIFORNIA AND DIVERSEY' :{'roads':['3120 West', '3242 North'], 
                    'protected_turn':2, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':1, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          }, 
    
    
    
'CALIFORNIA AND PETERSON' :{'roads':['2314 West', '5831 North'], 
                    'protected_turn':4, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          }, 
    
    
    
'CANAL AND ROOSEVELT':{'roads':['412 West', '460 South'], 
                    'protected_turn':4, 
                    'total_lanes':10, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          }, 
    
    
    
'CENTRAL AND ADDISON':{'roads':['5434 West', '3501 North'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          }, 
    
    
'CENTRAL AND BELMONT':{'roads':['5532 West', '3501 North'], 
                    'protected_turn':4, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          },
    
'CENTRAL AND CHICAGO':{'roads':['4444 West', '643 North'], 
                    'protected_turn':0, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          }, 
    
    
    
'CENTRAL AND DIVERSEY':{'roads':['5900 West', '2459 North'], 
                    'protected_turn':4, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          }, 
    
    
'CENTRAL AND FULLERTON':{'roads':['5400 West', '2366 North'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          }, 
    
    
'CENTRAL AND IRVING PARK':{'roads':['5301 West', '3658 North'], 
                    'protected_turn':4, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          }, 

'CENTRAL AND LAKE':{'roads':['5838 West', '643 North'], 
                    'protected_turn':1, 
                    'total_lanes':6, 
                    'medians':1, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':1, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                          },    

'CENTRAL AND MILWAUKEE':{'roads':['5601 West', '5601 North'], 
                    'protected_turn':1, 
                    'total_lanes':10, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':5, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':1,
                    'triangle':1,
                          },  
 
    
    
'CERMAK AND PULASKI':{'roads':['4042 West', '2119 South'], 
                    'protected_turn':1, 
                    'total_lanes':8, 
                    'medians':2, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':1,
                          },  
    

'CHICAGO AND CLARK':{'roads':['54 West', '835 North'], 
                    'protected_turn':1, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':2,
                          },  

    
'CICERO AND 47TH':{'roads':['4706 West', '4310 South'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':0,
                          },  
    
    
    
'CICERO AND ADDISON':{'roads':['4550 West', '3647 North'], 
                    'protected_turn':4, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':0,
                          },  
    
    
'CICERO AND ARMITAGE':{'roads':['4459 West', '2125 North'], 
                    'protected_turn':2, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':0,
                          },  
    
'CICERO AND CHICAGO':{'roads':['4444 West', '1125 North'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':0,
                          },  

'CICERO AND DIVERSEY':{'roads':['4632 West', '2845 North'], 
                    'protected_turn':4, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':0,
                          }, 
    
    
'CICERO AND FULLERTON':{'roads':['4710 West', '2125 North'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':0,
                          }, 
    
'CICERO AND HARRISON':{'roads':['4631 West', '815 South'], 
                    'protected_turn':0, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':0,
                          }, 
    
    
'CICERO AND I55':{'roads':['4310 South', '4310 South'], # used same twice.  No data for ramp, but lots of traffic
                    'protected_turn':0, 
                    'total_lanes':8, 
                    'medians':2, 
                    'exit':1, 
                    'split':0, 
                    'way':4, 
                    'underpass':1, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':2,
                          }, 
    
'CICERO AND NORTH':{'roads':['4310 South', '4706 West'], # used nearby feeder 47th.  No data for ramp, but lots of traffic (approximation)
                    'protected_turn':0, 
                    'total_lanes':8, 
                    'medians':2, 
                    'exit':1, 
                    'split':0, 
                    'way':4, 
                    'underpass':1, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':2,
                          }, 
    
'CICERO AND PETERSON':{'roads':['5800 North', '4850 West'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':1, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':0,
                          }, 
    
'CICERO AND WASHINGTON':{'roads':['25 North', '3935 West'], 
                    'protected_turn':0, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':0,
                          }, 
    
    
'CLARK AND FULLERTON':{'roads':['3733 North', '500 West'], 
                    'protected_turn':0, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':2,
                    'angled':0,
                    'triangle':0,
                     'one_way':0,
                          }, 
    
    
'CLARK AND IRVING PARK':{'roads':['3733 North', '1140 West'], 
                    'protected_turn':4, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':2,
                    'angled':1,
                    'triangle':0,
                     'one_way':0,
                          }, 
    
'COLUMBUS AND ILLINOIS':{'roads':['745 North', '242 East'], # subsituted E/W w/ Grand (no data), N/S is up by hospital (poor data)
                    'protected_turn':1, 
                    'total_lanes':9, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':1, 
                    'no_left':1,
                    'angled':0,
                    'triangle':0,
                     'one_way':3,
                          }, 
    
'CORNELL DRIVE AND 57TH':{'roads':['1730 East', '1621 East'], # MSI.  This intersection is tricky.
                    'protected_turn':1, 
                    'total_lanes':6, 
                    'medians':1, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':1, 
                    'no_left':0,
                    'angled':1,
                    'triangle':0,
                     'one_way':0,
                          }, 
    
'CORTLAND AND ASHLAND':{'roads':['1629 North', '1851 West'], # My second least favorite intersection in all of Chicago
                    'protected_turn':1, 
                    'total_lanes':7, 
                    'medians':1, 
                    'exit':1, 
                    'split':0, 
                    'way':5, 
                    'underpass':2, 
                    'no_left':0,
                    'angled':1,
                    'triangle':1,
                     'one_way':1,
                          },
    
    
    
'COTTAGE GROVE AND 71ST':{'roads':['7141 South', '7150 South', '240 East'], 
                    'protected_turn':2, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':6, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':1,
                    'triangle':1,
                     'one_way':0,
                          },
    

    
    
'COTTAGE GROVE AND 95TH':{'roads':['9401 South', '1057 East'], 
                    'protected_turn':3, 
                    'total_lanes':8, 
                    'medians':1, 
                    'exit':0, 
                    'split':0, 
                    'way':3, 
                    'underpass':1, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':0,
                          },
    
    
'DAMEN AND 63RD':{'roads':['6559 South', '2237 West'], 
                    'protected_turn':1, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':0,
                          }, 
    
    
'DAMEN AND DIVERSEY':{'roads':['1614 West', '3137 North', '2293 North'], 
                    'protected_turn':0, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':6, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':1,
                    'triangle':1,
                     'one_way':0,
                          },
    
'DAMEN AND ELSTON':{'roads':['3249 North', '3137 North'], # Elston then Damen, both north, but at right angle here.  Odd intersect
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':1,
                     'one_way':0,
                          },   

    
'DAMEN AND FULLERTON':{'roads':['3249 North', '1434 West'], 
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':1,
                     'one_way':0,
                          },  
    
    
'DIVERSEY AND AUSTIN':{'roads':['2653 North', '6041 West'], 
                    'protected_turn':0, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':0,
                          },  
    
'DIVERSEY AND WESTERN':{'roads':['3260 North', '1614 West', '3249 North'], 
                    'protected_turn':2, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':6, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':1,
                    'triangle':1,
                     'one_way':0,
                          },  
    
'DIVISION AND DAMEN':{'roads':['1508 North', '1925 West'], 
                    'protected_turn':0, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':0,
                          }, 

'DIVISION AND DAMEN':{'roads':['1508 North', '1925 West'], 
                    'protected_turn':0, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':0,
                          }, 
    
'ELSTON AND ADDISON':{'roads':['3249 North', '3023 West'], 
                    'protected_turn':2, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':1,
                    'triangle':1,
                     'one_way':0,
                          }, 
    
'ELSTON AND FOSTER':{'roads':['5110 North', '4856 West'], 
                    'protected_turn':0, 
                    'total_lanes':7, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':5, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':1,
                    'triangle':1,
                     'one_way':1,
                          }, 
    
'ELSTON AND IRVING PARK':{'roads':['4050 North', '3842 West'],   # no info on small street
                    'protected_turn':2, 
                    'total_lanes':7, 
                    'medians':2, 
                    'exit':0, 
                    'split':0, 
                    'way':6, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':1,
                    'triangle':1,
                     'one_way':1,
                          }, 
    
    
'ELSTON AND LAWRENCE':{'roads':['4464 North', '4245 West'],   
                    'protected_turn':2, 
                    'total_lanes':5, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':5, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':1,
                    'triangle':1,
                     'one_way':1,
                          }, 

    
'FOSTER AND BROADWAY':{'roads':['1059 West', '5243 North'],   
                    'protected_turn':1, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':0,
                          }, 
    
    
'FOSTER AND NAGLE':{'roads':['6058 West', '5205 North'],   # chose not to make a triangle, because it is not major artery triangle
                    'protected_turn':2, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':0,
                          }, 
    
'FOSTER AND NORTHWEST HIGHWAY':{'roads':['5313 West', '2761 North'],   
                    'protected_turn':0, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':1,
                     'one_way':0,
                          }, 
    
    
'FULLERTON AND NARRAGANSETT':{'roads':['6325 West', '4810 North'],   
                    'protected_turn':0, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,  # big triangle again 150m cutoff
                     'one_way':0,
                          }, 
    
    
'GARFIELD AND ASHLAND':{'roads':['1440 West', '5323 South'],  
                    'protected_turn':2, 
                    'total_lanes':10, 
                    'medians':4, 
                    'exit':0, 
                    'split':1, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':0,
                          }, 
    
    
'GRAND AND OAK PARK':{'roads':['6325 West', '1928 North'],  
                    'protected_turn':0, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':0,
                          }, 
    
    
'HALSTED AND 103RD':{'roads':['646 West', '10621 South'],  
                    'protected_turn':3, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':0,
                          }, 
    
    
'HALSTED AND 63RD':{'roads':['519 West', '6020 South'],  
                    'protected_turn':3, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                     'one_way':0,
                          }, 
    
    
'HALSTED AND 83RD':{'roads':['1101 West', '8357 South'],  
                    'protected_turn':0, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                    'one_way':0,
                    'turn_lanes':4,
                    'lat': 41.74335288466016, 
                    'long':-87.6438925332591,
                          }, 

'HALSTED AND 95TH':{'roads':['948 West', '9550 South'],  
                    'protected_turn':4, 
                    'total_lanes':8, 
                    'medians':2, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                    'one_way':0,
                    'turn_lanes':4,
                    'lat': 41.72150888963739, 
                    'long':-87.64313109186868,
                          }, 

    
    
'HALSTED AND DIVISION':{'roads':['624 West', '840 North'],  
                    'protected_turn':2, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                    'one_way':0,
                    'turn_lanes':4,
                    'lat': 41.903623493201046, 
                    'long':-87.64804876057735,
                          }, 
    
'HALSTED AND FULLERTON':{'roads':['500 West', '2034 North', '2136 North' ],  
                    'protected_turn':2, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':1,
                    'triangle':1,
                    'one_way':0,
                    'turn_lanes':6,
                    'lat': 41.92543431193316, 
                    'long':-87.6487053182209,
                          }, 
    
    
'HALSTED AND MADISON':{'roads':['600 West', '159 North'],  
                    'protected_turn':3, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':1, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                    'one_way':0,
                    'turn_lanes':4,
                    'lat': 41.88177823902311, 
                    'long':-87.64736954299323,
                          }, 

    
'HALSTED AND NORTH':{'roads':['929 West', '2034 North'],  
                    'protected_turn':3, 
                    'total_lanes':5, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':1,
                    'one_way':0,
                    'turn_lanes':4,
                    'lat': 41.91091037980912, 
                    'long':-87.64832218572224,
                          }, 
    
'HAMLIN AND LAKE':{'roads':['3837 West', '114 North'],  
                    'protected_turn':0, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':2, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                    'one_way':0,
                    'turn_lanes':0,
                    'lat': 41.88523875773175, 
                    'long':-87.7209141023015,
                          },  
    
'HAMLIN AND MADISON':{'roads':['3932 West', '114 North'],  
                    'protected_turn':0, 
                    'total_lanes':6, 
                    'medians':1, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                    'one_way':0,
                    'turn_lanes':4,
                    'lat': 41.880782902944695, 
                    'long':-87.7207221547585,
                          },  
    
    
'HARLEM AND BELMONT':{'roads':['7368 West', '3250 North'],  
                    'protected_turn':4, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                    'one_way':0,
                    'turn_lanes':4,
                    'lat': 41.937994907742684, 
                    'long':-87.80677025078413,
                          },  
    
'HARLEM AND NORTHWEST HWY':{'roads':['6516 North', '6805 North'],  
                    'protected_turn':2, 
                    'total_lanes':4, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':1,
                    'angled':1,
                    'triangle':1,
                    'one_way':0,
                    'turn_lanes':2,
                    'lat': 41.99701477642295, 
                    'long':-87.8068385869584,
                          },  

    
'HOLLYWOOD AND SHERIDAN':{'roads':['1050 West', '5333 North'],  
                    'protected_turn':1, 
                    'total_lanes':7, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':2,
                    'angled':0,
                    'triangle':0,
                    'one_way':0,
                    'turn_lanes':1,
                    'lat': 41.985552068308856,  
                    'long':-87.65525167530868,
                          },  

        
'HOMAN/KIMBALL AND NORTH':{'roads':['3335 West', '1820 North'],  
                    'protected_turn':0, 
                    'total_lanes':7, 
                    'medians':1, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                    'one_way':0,
                    'turn_lanes':3,
                    'lat': 41.910091106539824, 
                    'long':-87.71186977893635,
                          },  

        
'IRVING PARK AND CALIFORNIA':{'roads':['3056 West', '3765 North'],  
                    'protected_turn':4, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                    'one_way':0,
                    'turn_lanes':4,
                    'lat': 41.95400234758005, 
                    'long':-87.6982443011127,
                          },  
    
    
'IRVING PARK AND KEDZIE':{'roads':['3056 West', '4710 North'],  
                    'protected_turn':2, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0,
                    'one_way':0,
                    'turn_lanes':4,
                    'lat': 41.953909630791166, 
                    'long':-87.70800147472895,
                          },  
    
    
'IRVING PARK AND KILPATRICK':{'roads':['4240 West'],  # no info for kilpatrick  
                    'protected_turn':1, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0, # big triangle
                    'one_way':1,
                    'turn_lanes':3,
                    'lat': 41.95339512528642,
                    'long': -87.74463497408772,
                          }, 
    
    
'IRVING PARK AND LARAMIE':{'roads':['4240 West'],  # no info for kilpatrick  
                    'protected_turn':1, 
                    'total_lanes':6, 
                    'medians':0, 
                    'exit':0, 
                    'split':0, 
                    'way':4, 
                    'underpass':0, 
                    'no_left':0,
                    'angled':0,
                    'triangle':0, # big triangle
                    'one_way':1,
                    'turn_lanes':3,
                    'lat': 41.95339512528642,
                    'long': -87.74463497408772,
                          }, 
}






''' 

, 
,
, 
'IRVING PARK AND NARRAGANSETT',
'JEFFERY AND 79TH', 
'JEFFERY AND 95TH', 
'KEDZIE AND 26TH',
'KEDZIE AND 31ST', 
'KEDZIE AND 47TH', 
'KEDZIE AND 63RD',
'KEDZIE AND 71ST', 
'KEDZIE AND ARMITAGE', 
'KIMBALL AND DIVERSEY',
'KIMBALL AND LINCOLN', 
'KOSTNER AND NORTH', 
'LAFAYETTE AND 87TH',
'LAKE AND UPPER WACKER',
'LAKE SHORE DR AND BELMONT',
'LARAMIE AND FULLERTON',
'LARAMIE AND MADISON',
'LASALLE AND KINZIE',
'LAWRENCE AND CICERO',
'LAWRENCE AND WESTERN', 
'LINCOLN AND MCCORMICK',
'MADISON AND CENTRAL', 
'MADISON AND WESTERN',
'MICHIGAN AND JACKSON', 
'MICHIGAN AND ONTARIO',
'MILWAUKEE AND CENTRAL', 
'MILWAUKEE AND DEVON',
'MILWAUKEE AND MONTROSE', 
'MONTROSE AND WESTERN',
'NORTHWEST HIGHWAY AND FOSTER', 
'OGDEN AND KOSTNER',
'PERSHING AND WESTERN', 
'PETERSON AND WESTERN',
'PULASKI AND 63RD',
'PULASKI AND 79TH', 
'PULASKI AND ARCHER', 
'PULASKI AND ARMITAGE',
'PULASKI AND BELMONT', 
'PULASKI AND CHICAGO',
'PULASKI AND DIVERSEY', 
'PULASKI AND DIVISION',
'PULASKI AND FOSTER', 
'PULASKI AND FULLERTON',
'PULASKI AND IRVING PARK',
'PULASKI AND LAWRENCE',
'PULASKI AND MONTROSE', 
'PULASKI AND NORTH',
'PULASKI AND PETERSON',
'RIDGE AND CLARK', 
'ROOSEVELT AND HALSTED',
'ROOSEVELT AND KOSTNER', 
'ROOSEVELT AND PULASKI',
'SACRAMENTO AND CHICAGO', 
'SACRAMENTO AND LAKE',
'SHERIDAN AND FOSTER', 
'STATE AND 79TH', 
'STONEY ISLAND AND 76TH',
'STONEY ISLAND AND 79TH',
'STONY ISLAND/CORNELL AND 67TH',
'TOUHY AND OSCEOLA', 
'VAN BUREN AND WESTERN',
'VINCENNES AND 111TH', 
'WENTWORTH AND GARFIELD',
'WESTERN AND 51ST', 
'WESTERN AND 63RD', 
'WESTERN AND 71ST',
'WESTERN AND 79TH', 
'WESTERN AND ADDISON',
'WESTERN AND ARMITAGE',
'WESTERN AND CERMAK',
'WESTERN AND CHICAGO',
'WESTERN AND DEVON',
'WESTERN AND FOSTER', 
'WESTERN AND FULLERTON',
'WESTERN AND MARQUETTE', 
'WESTERN AND NORTH',
'WESTERN AND PRATT',
'WESTERN AND TOUHY'

'''